// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnrhecawcfklmjxasbdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImducmhlY2F3Y2ZrbG1qeGFzYmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NjA0NDUsImV4cCI6MjA3MTEzNjQ0NX0.4TFPA_hidqgYjN8w6M1pezux26H-kYlTuMHPxfiJqRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});